title: Sue's Notebook
description: On software architecture, living documentation and sustainable software design.

markdown: kramdown
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/articles/page:num/"